<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qcmpresentation" nsURI="http://www.example.org/qcmpresentation"
    nsPrefix="qcmpresentation">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="QuestionnairePresentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showProgressBar" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableBackNavigation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//QuestionPage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultPage" eType="#//ResultPage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="headerNotEmpty"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="headerNotEmpty" value="header.size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cssClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuestionPage" eSuperTypes="#//Page">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="questionTextNotEmpty minimumTwoOptions hasCorrectAnswer correctInputType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="questionTextNotEmpty" value="questionText.size() > 0"/>
      <details key="minimumTwoOptions" value="options->size() >= 2"/>
      <details key="hasCorrectAnswer" value="options->exists(o | o.correct)"/>
      <details key="correctInputType" value="&#xA;&#x9;&#x9;&#x9;if multipleChoice then&#xA;        &#x9;&#x9;options->forAll(o | o.inputType = InputType::CHECKBOX)&#xA;    &#x9;&#x9;else&#xA;        &#x9;&#x9;options->forAll(o | o.inputType = InputType::RADIO)&#xA;    &#x9;&#x9;endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="questionText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difficultyDisplay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//AnswerOption" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleChoice" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnswerOption">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="answerTextNotEmpty"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="answerTextNotEmpty" value="text.size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correct" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputType" eType="#//InputType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultPage" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showDetailedFeedback" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showCorrectAnswers" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scoreDisplay" eType="#//ScoreDisplayType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InputType">
    <eLiterals name="RADIO"/>
    <eLiterals name="CHECKBOX" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScoreDisplayType">
    <eLiterals name="PERCENTAGE"/>
    <eLiterals name="FRACTION" value="1"/>
    <eLiterals name="SIMPLE_TEXT" value="2"/>
  </eClassifiers>
</ecore:EPackage>
